version: '3.7'
services:
  db:
    image: postgres:12.5
    command: ['postgres', '-c', 'log_statement=all']
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: math_gen
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
